name: iOS Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"

      - name: Install Flutter dependencies
        run: |
          cd flutter_module
          flutter pub get

      - name: Build Flutter module
        run: |
          cd flutter_module
          flutter build ios-framework --no-debug --output=./build/ios-framework

      - name: Prepare iOS dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Ensure shared Xcode scheme
        run: |
          cd ios
          mkdir -p QRApp.xcworkspace/xcshareddata/xcschemes
          cp QRApp.xcodeproj/xcshareddata/xcschemes/QRApp.xcscheme QRApp.xcworkspace/xcshareddata/xcschemes/ || true

      - name: Build iOS app
        run: |
          xcodebuild clean build \
          -workspace ios/QRApp.xcworkspace \
          -scheme QRApp \
          -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_IDENTITY=""

      - name: Run iOS tests
        run: |
          xcodebuild test \
          -workspace ios/QRApp.xcworkspace \
          -scheme QRApp \
          -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
          CODE_SIGNING_ALLOWED=NO
